-- CreateTable
CREATE TABLE "PrePaciente" (
    "id" SERIAL NOT NULL,
    "nome" TEXT,
    "email" TEXT,
    "endereco" TEXT,
    "nascimento" TIMESTAMP(3),
    "idade" TEXT,
    "cpf" TEXT,
    "telefone" TEXT,
    "emergencia" TEXT,
    "generoOrientacao" TEXT,
    "estadoCivil" TEXT,
    "origemConhecimento" TEXT,
    "preocupacao" TEXT,
    "motivoAtendimento" TEXT,
    "experienciaAnterior" TEXT,
    "saudeFisica" TEXT,
    "detalhesSaudeFisica" TEXT,
    "medicamentos" TEXT,
    "diagnosticoMental" TEXT,
    "historicoFamiliar" TEXT,
    "rotina" TEXT,
    "sono" TEXT,
    "atividadeFisica" TEXT,
    "estresse" TEXT,
    "convivencia" TEXT,
    "relacaoFamiliar" TEXT,
    "apoioSocial" TEXT,
    "nivelFelicidade" TEXT,
    "ansiedade" TEXT,
    "pensamentosNegativos" TEXT,
    "objetivoTerapia" TEXT,
    "temasDelicados" TEXT,
    "estiloAtendimento" TEXT,
    "observacoesFinais" TEXT,
    "autorizacaoLGPD" BOOLEAN,
    "habilitado" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PrePaciente_pkey" PRIMARY KEY ("id")
);
